#!/usr/bin/env bash
# Script that gives information about the "holbertonschool" file
fl=holbertonschool
if [ -e $fl ]; then
   echo "school file exists"
   if [ -s $fl ]; then
      echo "school file is not empty"
   else
      echo "school file is empty"
   fi
   if [ -f $fl ]; then
      echo "school is a regular file"
   fi
else
	echo "school file does not exist"
fi
